### ISSUE TITLE
If you enable the extension, pages are loaded for a very long time.

### ISSUE THREAD

**Issue by Chelovek10000** [fastaddons/AutoHighlight#13]
If you enable the extension, pages are loaded for a very long time.
I have added 250 words with the same rules (working mainly with Linkedin)
With the expansion, the pages load for about a minute. No extension - a few seconds. Can I somehow fix this with the help of settings?

**Comment by Chelovek10000** [comment]
I understand you. Thank you very much for your work. This extension is very useful)

**Comment by fastaddons** [comment]
The new version 4.4 has been released in Firefox Store, Chrome store version will be released after review, probably in a day or two.
In this version, I've added new option to use the new library from the pull-request above.
Try to activate this option and let me know if the helps or if it breaks anything.
![image](https://user-images.githubusercontent.com/55486931/181905382-9f42e665-0122-4db5-acb4-ea2ed9c9f714.png)
