### ISSUE TITLE
Highlightning doesn't work with iframes on Chrome

### ISSUE THREAD

**Issue by peace2000** [fastaddons/AutoHighlight#16]
**Describe the bug**  
If a page uses internal iframe (not sure how it works with external iframes), no content will be highlighted in the whole page. This only occurs on Chrome. Firefox doesn't have this issue.

**Steps To Reproduce**  
1. Open https://www.w3schools.com/html/tryit.asp?filename=tryhtml_iframe_height_width_css
2. Make a rule to highlight "You can"
3. "You can" won't be highlighted on the right side of the page, only on the left side. Firefox has no issues, Chrome has. Doesn't work even if I enable "Every page" -mode.

Firefox:
![image](https://user-images.githubusercontent.com/17256841/192248900-0f27129d-cf10-410e-b0ee-05167db3bbc0.png)

Chrome:

![image](https://user-images.githubusercontent.com/17256841/192248992-238acfc3-00b9-40f3-9f5e-c335e67c3b80.png)

**Expected behavior**  
AH should highlight text on Chrome also on iframe-enabled pages. The right side should get highlighted.

**Device info:**
 - operating system: Win 10
 - Browser and version: Chrome 105.0.5195.127
 - ScrollAnywhere version: None

**Additional info**
I experienced this bug in a private, ServiceNOW based website so I cannot give a link to that. I could not find a sample page on a public web that uses similar internal iframe as well so I linked to w3schools.com that "artificially" reproduces this issue. Hopefully it's ok this way, the demo page link reproduces the issue exactly in the same way as in the page I'm using.

**Comment by fastaddons** [comment]
**Thanks for reporting!**
It seems I have a bug in the injection code in Chrome. It's using a different API and it looks like I'm not targeting correct frame...

I will try to fix this by the end of this week, (maybe even today if I still have enough strength when I get home).

**Comment by fastaddons** [comment]
So, I've fixed something... but something else is still broken :).
The page has 3 frames, 1 main page, 2 the right part and 3 the nested iframe in the right part.
Somehow, Chrome doesn't send me event for the second one... maybe because it doesn't have a "src" attribute? I have to say I'm surprised that's a thing :).
In any case, new 4.6 version fixes highlights in normal iframes, like the nested one, so it should help in most cases. Let me know if it helped you as well.
Chrome and Edge versions are being reviewed now.

**Comment by peace2000** [comment]
Cool! Thanks again, after the new version becomes available, I'll inform what happened with the site I'm using this with.

**Comment by fastaddons** [comment]
New version is available now, I hope it helps :)

**Comment by peace2000** [comment]
Hi, I noticed and already tested, this seemed to work for me, but I'd also want another person to confirm this. I'll notify when he checks this as well.

**Comment by peace2000** [comment]
@fastaddons 

Hi, got confirmation that it also works another person. Thanks!

I do agree that this will fix it for most of the cases. Good work!
