### ISSUE TITLE
List of pages with highlights and sync with firefox addon storage

### ISSUE THREAD

**Issue by megamorphg** [fastaddons/AutoHighlight#17]
**Is your feature request related to a problem? Please describe.**
Not sure where the highlights are stored but it would be great to know that it is safe and synced somewhere. If firefox storage is insufficient to store highlight data, it would be great to have some other sort of backup process.

Typically highlights are made for reviewing later in my case so it would be great to have a way to:
1. see all previous pages with highlights
2. date last time page was opened

**Describe the solution you'd like**
List within add-on main button or a separate extension page

**Describe alternatives you've considered**
Bookmarking pages for review and managing within this or Tab Snooze

**Additional context**

**Comment by fastaddons** [comment]
Hello,
The highlights are stored in the Firefox Sync (see also Settings / "Storage icon" item), so they should be safe and they are will synchronize across your devices, except for Android where Firefox Sync doesn't work for addons data.

But I'm a bit confused about that feature request, could you explain it more please?
