### ISSUE TITLE
regex matching numeric range does not highlight

### ISSUE THREAD

**Issue by Paladin-z** [fastaddons/AutoHighlight#19]
Regex to match a numeric range does not hightlight matching dates.

The regex used is `/(19[1-7]\d)/` - Date ranges between 1910 & 1979 should be highlighted.

Even `/(1930|1931|1932|1933|1934|1935|1936|1937|1938|1939)/` doesn't match dates between 1930-1939

**Device info:**
 - Windows 10 
 - Firefox  107.0.1 (64-bit)
 - Auto Highlight version: 4.5

**Comment by fastaddons** [comment]
Did you enabled "RegExp" option (checkbox)?
Also, those "/" at the beginning and end are part of the regexp? Try it without it.

**Comment by Paladin-z** [comment]
I did have it enabled and removing the /'s resolved it, thanks!
