### ISSUE TITLE
Disable Numbers Counting for single Highlight or for All

### ISSUE THREAD

**Issue by o-data** [fastaddons/AutoHighlight#21]
**Is your feature request related to a problem? Please describe.**
With certain Highlight I'm getting hundreds of results.

**Describe the solution you'd like**
I don't need to know how many number sometimes, so maybe we can either disable it altogether or only show Numbers for one which have setting enable.

**Describe alternatives you've considered**
Disable Count.

**Additional context**
![image](https://user-images.githubusercontent.com/67723461/213869631-f6d7a538-e126-49ef-9d48-619844f1cf22.png)

---
Thank you

**Comment by fastaddons** [comment]
Hello,
I guess the badge number can be distracting.
I'll add option to disable it completely.

**Comment by fastaddons** [comment]
Done, 4.7 version will have new option "Disable icon badge (number of highlighted words)".
I should release it soon.
