### ISSUE TITLE
Color tag text when editing post

### ISSUE THREAD

**Issue by Valus3000** [fastaddons/AutoHighlight#24]
**Describe the bug**  
If you edit a post that contains your highlighted word, in this case a member user_name of a forum (XenForo), the post/text would change to [COLOR=#E8F5E9FF]**user_name**[/COLOR] . Instead of just the user_name. If you edit a second time it add another color tag like [[COLOR=#E8F5E9FF][COLOR=#E8F5E9FF]**user_name**[/COLOR][/COLOR] . Only way to fix is to disable the addon then edit the post to remove the color tag then put back on the addon. Trying to remove the color tag without disabling the addon would remove the entire user_name and other tags.

**Steps To Reproduce**  
1. Add a member name from a forum to the addon
2. Quote the person post / reply to the person
3. Post your reply
4. Edit your reply / quote of the person
5. The color tag problem shows in their user name

**Expected behavior**  
I expect when you edit the post/quote you would not see the color tag and just the color of the person user_name as it was the first time you reply/quote.

**Device info:**
 - operating system: Windows 10 x64
 - Browser and version: Firefox v111.0 x64
 - Auto Highlight version: v4.7

**Additional info**
Attach some screenshot of initial quote/reply then another image showing what happens when you edit the post.

**How it suppose to look / Originally looks:**
![1](https://user-images.githubusercontent.com/64745918/226084132-4c538c31-4e8e-4b3b-996d-15af216914c7.png)

**After you edit the post to maybe say more or mention something else:**
![2](https://user-images.githubusercontent.com/64745918/226084168-81626827-95b9-4aac-adc8-8e5e98d4c144.png)

**If you edit a 3rd time without fixing the problem by disabling the addon and remove previous color text:**
![3](https://user-images.githubusercontent.com/64745918/226084187-89e11b7f-2508-4c28-811f-b56b56d413a7.png)

**Comment by Juraj-Masiar** [comment]
Hello,
I don't think Firefox update could break that, it's more likely that they have changed something.
In any case, new version 4.8 will now skip editable HTML fields by default, so that should help.
It was just released for Firefox.
