### ISSUE TITLE
Add a excluded-site list.

### ISSUE THREAD

**Issue by SakuraWald** [fastaddons/AutoHighlight#25]
**Is your feature request related to a problem? Please describe.**
Some websites will be rendered in-correctly if I enable AutoHighlight.

**Describe the solution you'd like**
Simply add a exclude-site list for AutoHighlihgt.

**Describe alternatives you've considered**
Delay the render process until the whole page is loaded fully. (I am not sure if this is a render sequences problem)

**Additional context**
None.

**Comment by Juraj-Masiar** [comment]
Hello,
Could you send me some example pages where I could reproduce the issue?
Thanks :)

**Comment by Juraj-Masiar** [comment]
Oh, that's crazy bad!
But how do I fix this...
There is no "official integration" with page-generated content so the addon can't tell if the bot is done generating content.
I'll see what I can do, but so far I can't think of anything :(

**Comment by SakuraWald** [comment]
How about add a domain  blacklist ?

**Comment by Juraj-Masiar** [comment]
Good idea :)
Although it doesn't solve the problem, it's better than nothing.
I've didn't build blacklist so far because I don't really use global rules, only domain specific, so I never felt the need.
I'll try to build a quick one for the upcoming release.

**Comment by SakuraWald** [comment]
Thank you ! This is a very awesome work for readers.

**Comment by Juraj-Masiar** [comment]
Done, you can now exclude current page from highlighting:
![image](https://user-images.githubusercontent.com/6358971/232413216-b0e4f4b6-9c49-42a3-a261-cf6ceb314acc.png)

It's part of the 4.8 release - already available for Firefox, Chrome and Edge should be approved soon (maybe few hours/days).
