### ISSUE TITLE
✋, Can you develop an extension for Page - Remark/Note/Sticky/Annotation/comment ?

### ISSUE THREAD

**Issue by dnknn** [fastaddons/AutoHighlight#3]
> ✋,~ Juraj Mäsiar !  sorry for my English..... Thank you very much for developing the [AutoHighlight](https://chrome.google.com/webstore/detail/ndndibnggapaodjdfoeehgmmpppedgfb) extension, It is very easy/useful/highly customizable etc, UI flavor is also great, the most important thing is to support URL matching mode (e.g. RegExp), Thanks again for your great work ❣

This feature request can almost be implemented directly using [AutoHighlight](https://chrome.google.com/webstore/detail/ndndibnggapaodjdfoeehgmmpppedgfb)'s architecture template, so I post it directly here ^_^

### Page _Remark/Note/Sticky/Annotation/comment feature:

<details><summary>online demo</summary>
　

[http://postitall.txusko.com/extension.html](http://postitall.txusko.com/extension.html)

![image](https://user-images.githubusercontent.com/10995302/110686192-210a0f00-821a-11eb-83f6-a84e6c2cf400.png)</details>  

![page-note](https://user-images.githubusercontent.com/10995302/110686746-b907f880-821a-11eb-8b31-dfe333b43fb2.gif) 
- 👆 From userscript: [Write a note!](https://greasyfork.org/scripts/92)  (this is the simplest/lightweight/mini function implementation)

![1](https://user-images.githubusercontent.com/10995302/110686717-b0afbd80-821a-11eb-95d6-996bcd914428.gif)
- 👆 From extension: [Web Page Sticky Notes
](https://chrome.google.com/webstore/detail/alpjieidnmmkljnceakgpeajlngabnee)

- Other similar extensions: [Post It All : Sticky notes](https://chrome.google.com/webstore/detail/ifbdckgghfmehefajfoichlhcdiibkoc)  

- [A lot of search results at the webstore](https://chrome.google.com/webstore/search/note%20%20Sticky%20?_category=extensions)

----

> Yes, there are indeed many such extensions, but after I searched all of them and tried them one by one, I finally found that **none** of them supports URL matching (applied to). 
And most of them have very poor performance (more lethality and greater impact on the performance of the page, e.g. high CPU/RAM usage) , so I gave up all of them. 

<img align=right width=40% src=https://user-images.githubusercontent.com/10995302/110689961-4a2c9e80-821e-11eb-93c4-462f0d6892e2.png>

- There are many, **but none** of them can support free URL matching (applied to), so should we do something?

🗣 The URL matching (applied to) mode, it is just like AutoHighlight (seeing the screenshot)👉

- I like your extension UI flavor and the URL match mode, can you develop an extension based on Auto Highlight to achieve this feature ❓	

>  Yes, I also know your [Private Notes](https://chrome.google.com/webstore/detail/phckehehoioleicpfnmigmidofibnnnn), but it is an extension of two different types and user groups,
> I don't know if you are interested in this (develop this project) ... ^_^

The most important thing is to support URL free matching mode, especially to support RegExp, 
I personally think it will be very popular with users.
Because some remarks only want to be applied to certain pages or not to certain pages, or only to specific pages, Obviously, only a powerful tool like `RegExp` can do it!

In addition, if you are interested, can also support the matching mode of `if (document.title == 'xxxxx' ) {.......}`

<details><summary>Details</summary>

![image](https://user-images.githubusercontent.com/10995302/110691142-bbb91c80-821f-11eb-845d-681ea83a4bd3.png)</details>  

----

- In short, all functions are based on URL matching mode(must can support RegExp) as the premise, just like AutoHighlight.

- Can also have temporary functions like AutoHighlight :
![213_11042025](https://user-images.githubusercontent.com/10995302/110692239-1e5ee800-8221-11eb-9dd5-829889da6757.png)

- In addition, performance is also critical, i.e. will not have any major impact on the performance of the page, and the CPU/RAM occupancy rate will not be very high. (👍I believe your new technology💪 ^_^)
![213_11052241](https://user-images.githubusercontent.com/10995302/110699441-d2fd0780-8229-11eb-8016-04142ef00c28.png)

---

I have been looking for this kind of extension that can support RegExp matching, but it has never appeared, so I am looking forward to your reply. 
I wonder if you are willing to use your new technology to develop this kind of project ❓

**Comment by fastaddons** [comment]
Hello,
I see also some emails from you :). Thank you for such a nice words, but I don't think this is a good idea.
If I had unlimited time then sure. But I'm very busy with my existing projects. Plus my savings are gone and I need to start thinking about my future. Being an extension developer doesn't really earn much money :(.

The best what you can do is contact authors of those extensions and ask them to add these features.
The regular expressions are build in feature of JavaScript so adding it to existing extension should not be a problem.

Look here, this is one of the guys developing notes extension right now:
https://discourse.mozilla.org/t/performance-optimization-multiple-browser-storage-queries-vs-caching-everything-in-background-script/76435
It's always best to find someone who has passion for the specific extension and help him upgrade it.

**Comment by dnknn** [comment]
Hello @fastaddons , Thanks for your reply! very sorry😭, and I can understand you!

But I still think that this note feature can be easily transplanted from [AutoHighlight](https://chrome.google.com/webstore/detail/ndndibnggapaodjdfoeehgmmpppedgfb) , only the function is changed from [`AutoHighlight`](https://chrome.google.com/webstore/detail/ndndibnggapaodjdfoeehgmmpppedgfb)  to `notes`. This is equivalent to template cloning. 

Because I think the cost of developing this extension will not be too high, that’s why I dare to make this kind of request ... 🤦

At last, I still hope to consider this potential demand, because your extension works are not only lighter, but also rich Contagious, the UI is also beautiful, and easy to use.

---

> You can close this issue at any time...  

-  If one day you want to develop this extension, please let me know ^_^!


thanks again!
