### ISSUE TITLE
Rename entries in context menu

### ISSUE THREAD

**Issue by sojusnik** [fastaddons/AutoHighlight#4]
When using the context menu of the latest Firefox, then you'll see three options:
Auto Highlight "…"
Temporally Highlight "…"
Temporally Highlight everywhere "…"

I suggest renaming them to:
Highlight "…"
Temporally highlight "…"
Temporally highlight everywhere "…"

… for consistency reasons.

**Comment by fastaddons** [comment]
Hello,
Thanks for pointing this out. 
It will more clear without the uppercase and "Auto".
I'll fix this in the upcoming release 2.5

**Comment by fastaddons** [comment]
2.5 has been released for Firefox, Chrome is still reviewing
