### ISSUE TITLE
Usage without the restrictive cloud storage Firefox Sync

### ISSUE THREAD

**Issue by SWatB-com** [fastaddons/AutoHighlight#41]
Please add the ability to use without the limitation imposed by cloud storage Firefox Sync. Perhaps, let the extension switch to local storage mode if the cloud storage is filled to capacity. Or make it possible to manually enable/disable cloud storage Firefox Sync. Or use a combination, so that the priority works through cloud storage Firefox Sync, and the rest works locally. Otherwise, for a large number of words, I still have to use the "Multi Find: Search, Highlight, Explore" extension, which saves locally.

**Comment by Juraj-Masiar** [comment]
It's already there, see Settings / Options / Storage - switch to local.

**Comment by SWatB-com** [comment]
Thank you.
How to make exact word highlighting in RegExp mode?

**Comment by Juraj-Masiar** [comment]
I think you'll need to use some word boundary character, for example:
```
\bEXAMPLE\b
```

**Comment by SWatB-com** [comment]
Not convenient. Especially since all my words are in lowercase. The letter "b" blends with the rest. Maybe it's better to add some button with the command "highlight phrases entirely"?

**Comment by Juraj-Masiar** [comment]
There is option "Exact match" that should do something like that (I can't remember for sure).
But it won't work with RegExp option, since RegExp is a separate full programming language with its own rules.
Also I'm no expert on RegExp, it's super complex and challenging to use even for expert programmers :)

**Comment by SWatB-com** [comment]
For some reason, the \bEXAMPLE\b option does not work for me.
“RegExp” and “Across elements” are enabled.

**Comment by Juraj-Masiar** [comment]
Are you sure? I've just tested it here with `\bit\b` that will highlight only "it" words and it works fine.
Where did you tested it?

**Comment by SWatB-com** [comment]
Firefox.
I checked again and found that it works with Latin characters, but not with Cyrillic characters.

**Comment by Juraj-Masiar** [comment]
Interesting, it seems the Regex in javascript doesn't support Cyrillic or Hebrew:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#regular_expression_and_unicode_characters

I'll try to add the "u" flag they mention there to see how it behaves...

**Comment by SWatB-com** [comment]
Да, хорошо бы с этим что-то сделать.
Спасибо.
