### ISSUE TITLE
Font size doesn't apply to all sections

### ISSUE THREAD

**Issue by sojusnik** [fastaddons/AutoHighlight#5]
When adjusting the font size in the options, it doesn't change the font size in "Options", "Import/Export" and "Rules", but is applied in the remaining sections like "Help this project".

Happens on Firefox 86.0.1 on Ubuntu 20.10.

**Comment by fastaddons** [comment]
Yeah, I was hoping the library I use (Vuetify) will fix this somehow, but I guess I will have to patch it myself.
It will be fixed in the upcoming release 2.5

**Comment by fastaddons** [comment]
2.5 has been released for Firefox, Chrome is still reviewing
