### ISSUE TITLE
Texts in editable forms get removed instead of highlighted

### ISSUE THREAD

**Issue by peace2000** [fastaddons/AutoHighlight#7]
**Describe the bug**  
Saved texts that exist in user editable forms, will be removed when there's a match.

**Steps To Reproduce**  
1. Open a website that has saved texts in user editable form
2. Try to highlight a word in a form that has saved texts but that is user editable (e.g. try to set background-color for word "Data").

I'm using this app in a private website so can't give a direct link, but it's a ServiceNOW platform-based website, if you are familiar with such sites.

I saved a htm file from that website, that has an user editable form but I stripped everything else as it partly contained sensitive information :)

**Expected behavior**  
Auto Highlight would highlight saved texts in user editable forms as well.

**Device info:**
 - operating system: Windows 10
 - Browser and version: 78.15.0esr (64-bit)
 - ScrollAnywhere version: -

**Additional info**
Not a programmer by myself but it seems that AH does apply css values to that word but from user's perspective that word just disappears.

**Comment by peace2000** [comment]
[Phone Subscription.zip](https://github.com/fastaddons/AutoHighlight/files/7513462/Phone.Subscription.zip)

**Comment by fastaddons** [comment]
Hello,
Was this by any chance working before? I've released 2.7 just a few days ago so I wonder if it's related.

I remember I was solving this kind of issue some time ago and I remember it was pretty complicated.
I will check it out soon.

**Comment by peace2000** [comment]
Hi, I was using version 2.6. Updated now to 2.7 that suffers from the same issue.

I have been using this addon for a short moment so I can't be sure. Just happened to accidentally notice it today.

**Comment by fastaddons** [comment]
Thanks, I will look into it. 
But I have some urgent things to do right now so please be patient :)

**Comment by peace2000** [comment]
If it's not possible to highlight data in saved, editable form fields, it would be better to set AH to skip those fields completely so that no info would be hid. Of course I hope it's possible to make this work also in form fields properly :)

I can participate using any test releases id needed.

**Comment by peace2000** [comment]
Hi, ok take your time :)

**Comment by peace2000** [comment]
Hi, may I ask what's the situation concerning this one?

**Comment by fastaddons** [comment]
Hello,
I'm sorry for the huge delay. There is so much work to do, I have only a little time left for my smaller addons like this one.

Could you find some page where I could reproduce the problem? I've tried to make a whole page editable with `document.body.contentEditable = true` and then use the addon but it still works.

The file you've uploaded in the second comment is invalid HTML (I don't know how you stripped it but it's bad :)).

Also, the highlighting itself is done by a 3rd party library Mark.JS so there is chance I won't be able to fix it. I may be able to create some workaround, maybe the ignoring of editable fields.

**Comment by peace2000** [comment]
Hmm.. This is hard, because form fields like that are probably only found on pages that require an account...

Though, I was wondering... Also if you search something via Google, the search term in the form field doesn't activate:

![image](https://user-images.githubusercontent.com/17256841/189855697-db77f416-af62-4ef3-a452-a96dc2a8f88c.png)

https://www.google.com/search?q=term&ved=0ahUKEwjK9PyPsJH6AhUAQvEDHZ3hA_QQ4dUDCAY&oq=term&sclient=gws-wiz

I was wondering that maybe fixing that, could also fix this issue as well?

**Comment by peace2000** [comment]
I could try to save another html file but this time only cencor critical fields, not strip anything as I'm not probably good enough to do that properly :D

**Comment by peace2000** [comment]
Btw what do you mean by "invalid"? I get that file open. It might look strange but it's probably because it's missing all the extra files.

**Comment by peace2000** [comment]
Wait, I think I now found something that can be used for testings! Wikipedia.

Just open the edit page https://en.wikipedia.org/w/index.php?title=Talk:Text&action=edit

![image](https://user-images.githubusercontent.com/17256841/189875589-a4b07430-2752-4fd8-8534-d3e5d0c69a49.png)

Try to highlight word "Definition". In the first picture, that rule is off. But when I turn it on:

![image](https://user-images.githubusercontent.com/17256841/189875873-066d6db7-fe91-4965-bba4-876f5f2dfdbb.png)

All "Definition" words disappear, they don't get highlighted.

**Comment by fastaddons** [comment]
Nice! Thanks for the example, I can reproduce it here now.

So just to clarify, there are different types of "editable" inputs. In this case, it's "textarea" element which doesn't support any kind of styling, so it should be skipped completely.
This is 100% a bug and I'll do my best to fix it in the next release 4.5. I should have some "less busy time" till the end of this week so I will try to release it in this period.

**Comment by peace2000** [comment]
Awesome! That html sample I gave last year seems to be "textarea" a well. So it'll get fixed too.

**Comment by fastaddons** [comment]
Fixed version 4.5 has just been released for Firefox, Chrome and Edge are still reviewing the update (which may take a day or few).

New version skips all "textarea" elements, I'm not sure why was it even trying to highlight it when it's not possible... :)

**Comment by peace2000** [comment]
@fastaddons Seems to work. Great, thanks!
